name: Update Site
triggers:
- name: webhook
  type: webhook
  url: sample.io
  token: token
  headers:
  - name: User-Agent
    value: GitHub-Hookshot/b4238f9
image: ubuntu
env:
- name: FOO
  value: foo-value
workspace: /var/
script: |
  touch /Users/mac/zxj